---
title: "Baseball Report"
author: "Kyle Gilbert, Cole _, Dylan _"
highlight-style: github
format:
  html:
    code-fold: true
  pdf:
    geometry: 
      - top=30mm
      - left=30mm
editor: visual
---

```{r}
#| label: load-pkgs
#| code-summary: "Packages"
#| message: false
#| echo: false

library(tidyverse)
library(knitr)
library(ggplot2)
```

```{r}
#| label: load-datasets
#| echo: false

# Read in data
# Set working directory to path to repo
master <- read.csv("data/Master.csv")
salaries <- read.csv("data/Salaries.csv")
batting <- read.csv("data/Batting.csv")
batting_post <- read.csv("data/BattingPost.csv")
fielding <- read.csv("data/Fielding.csv")
fielding_of <- read.csv("data/FieldingOF.csv")
pitching <- read.csv("data/Pitching.csv")
pitching_post <- read.csv("data/PitchingPost.csv")

```
**Project Description:**

The goal of this final R project is to analyze the percentage of a team's salary cap allocated to specific players from 2000 to now and to explore the factors driving these players' compensation levels.